# Generated by Django 4.2.7 on 2024-01-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_myuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
