# Generated by Django 4.2.7 on 2024-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='notes',
            field=models.TextField(blank=True, default='Geen Notities', null=True),
        ),
    ]
