# Generated by Django 4.2.7 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='notes',
            field=models.TextField(default='Geen Notities'),
        ),
    ]
