# Generated by Django 4.2.7 on 2024-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_myuser_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Docent', 'Docent'), ('Student', 'Student'), ('Zakelijk', 'Zakelijk')], max_length=10, null=True),
        ),
    ]
