# Generated by Django 4.2.7 on 2023-12-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_klas_beschrijving'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datum', models.DateField()),
                ('eind_datum', models.DateField()),
                ('min_uren', models.IntegerField()),
                ('verwachte_uren', models.IntegerField()),
                ('stage_soort', models.CharField(max_length=100)),
                ('klas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.klas')),
            ],
        ),
    ]
