# Generated by Django 4.2.7 on 2024-01-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_bedrijf_name_alter_bedrijf_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrijf',
            name='stage_periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedrijven', to='homepage.stageperiode'),
        ),
    ]
