# Generated by Django 4.2.7 on 2024-01-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_bedrijf_zakelijk_gebruiker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.TextField()),
                ('start_datum', models.DateField()),
                ('eind_datum', models.DateField()),
                ('gevraagde_vaardigheden', models.TextField()),
                ('status', models.CharField(choices=[('Beschikbaar', 'Beschikbaar'), ('Vol', 'Vol')], default='Beschikbaar', max_length=20)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='homepage.bedrijf')),
            ],
        ),
    ]
