# Generated by Django 4.2.7 on 2024-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('status', models.CharField(choices=[('Afgewezen', 'Afgewezen'), ('Wachtend', 'Wachtend'), ('Aangenomen', 'Aangenomen')], max_length=20)),
            ],
        ),
    ]
